### PR TITLE
first version of networking module working on both native and browser

### PR DESCRIPTION
**Pull request by shuning-auki**

### CODE REVIEW

**Review by robinlindh — COMMENTED** [review]
Looks good to me. Would like for @jnkvca to check and approve it.

**Review by omusil24 — APPROVED** [review]

**Review by omusil24 — APPROVED** [review]

**Review by omusil24 — APPROVED** [review]

**Review by tatiesmars — COMMENTED** [review]
here is two feedback I think would be nice to have:
- support (optionally or not) IDs for all messages, and ensure no collision when generating it (as it can come from any peer at any time)
- support (optionally or not) message acknowledge for scenario that require TCP

**Review by tatiesmars — APPROVED** [review]
approved but it would be nice to consider adding what I mention in my previous comment in a following versions

**Comment by omusil24** [comment]
> here is two feedback I think would be nice to have:
> 
> * support (optionally or not) IDs for all messages, and ensure no collision when generating it (as it can come from any peer at any time)
> * support (optionally or not) message acknowledge for scenario that require TCP

The current protocol implemented in the PR is just a placeholder chat protocol, so I think we don't need to care about that here. We'll need to implement a proper protocol(s) utilizing protobufs/flatbuffers etc. later.

**Review by jnkvca — APPROVED** [review]

**Pull request merged**
